import type { ProcessingProfileConfig, ProfilePreset } from '../types';

export const PRESET_DEFAULTS: Record<Exclude<ProfilePreset, 'advanced'>, ProcessingProfileConfig> = {
  quick: {
    rejection_algorithm: 'sigma',
    rejection_low: 3.0,
    rejection_high: 3.0,
    normalization: 'addscale',
    drizzle_enabled: false,
    drizzle_scale: 2,
    drizzle_pixfrac: 0.7,
    debayer_pattern: 'auto',
    plate_solving_enabled: false,
    plate_solving_radius_deg: 30.0,
    plate_solving_speed: 'auto',
    gradient_removal_enabled: false,
    gradient_removal_method: 'polynomial',
    gradient_removal_ai_model: 'GraXpert-AI-1.0.0',
    stretch_method: 'auto',
    stretch_strength: 30,
    color_calibration_enabled: false,
    camera_defiltered: true,
    photometric_calibration_enabled: false,
    denoise_enabled: true,
    denoise_strength: 0.5,
    denoise_luminance_only: false,
    sharpen_enabled: false,
    sharpen_stellar_amount: 0.5,
    sharpen_nonstellar_amount: 0.7,
    sharpen_radius: 2,
    super_resolution_enabled: false,
    super_resolution_scale: 2,
    star_separation_enabled: false,
    star_separation_recombine: true,
    star_separation_nebula_weight: 0.8,
    star_separation_star_weight: 0.5,
    max_retries: 3,
  },

  standard: {
    rejection_algorithm: 'sigma',
    rejection_low: 3.0,
    rejection_high: 3.0,
    normalization: 'addscale',
    drizzle_enabled: false,
    drizzle_scale: 2,
    drizzle_pixfrac: 0.7,
    debayer_pattern: 'auto',
    plate_solving_enabled: true,
    plate_solving_radius_deg: 30.0,
    plate_solving_speed: 'auto',
    gradient_removal_enabled: true,
    gradient_removal_method: 'ai',
    gradient_removal_ai_model: 'GraXpert-AI-1.0.0',
    stretch_method: 'asinh',
    stretch_strength: 150,
    color_calibration_enabled: true,
    camera_defiltered: true,
    photometric_calibration_enabled: false,
    denoise_enabled: true,
    denoise_strength: 0.55,
    denoise_luminance_only: true,
    sharpen_enabled: true,
    sharpen_stellar_amount: 0.25,
    sharpen_nonstellar_amount: 0.30,
    sharpen_radius: 2,
    super_resolution_enabled: false,
    super_resolution_scale: 2,
    star_separation_enabled: false,
    star_separation_recombine: true,
    star_separation_nebula_weight: 0.8,
    star_separation_star_weight: 0.5,
    max_retries: 3,
  },

  quality: {
    rejection_algorithm: 'winsorized',
    rejection_low: 3.0,
    rejection_high: 3.0,
    normalization: 'addscale',
    drizzle_enabled: true,
    drizzle_scale: 2,
    drizzle_pixfrac: 0.7,
    debayer_pattern: 'auto',
    plate_solving_enabled: true,
    plate_solving_radius_deg: 30.0,
    plate_solving_speed: 'auto',
    gradient_removal_enabled: true,
    gradient_removal_method: 'ai',
    gradient_removal_ai_model: 'GraXpert-AI-1.0.0',
    stretch_method: 'asinh',
    stretch_strength: 180,
    color_calibration_enabled: true,
    camera_defiltered: true,
    photometric_calibration_enabled: false,
    denoise_enabled: true,
    denoise_strength: 0.65,
    denoise_luminance_only: true,
    sharpen_enabled: true,
    sharpen_stellar_amount: 0.45,
    sharpen_nonstellar_amount: 0.55,
    sharpen_radius: 2,
    super_resolution_enabled: false,
    super_resolution_scale: 2,
    star_separation_enabled: false,
    star_separation_recombine: true,
    star_separation_nebula_weight: 0.8,
    star_separation_star_weight: 0.5,
    max_retries: 3,
  },
};

export interface PresetFeature {
  label: string;
  enabled: boolean;
}

export const PRESET_FEATURES: Record<Exclude<ProfilePreset, 'advanced'>, PresetFeature[]> = {
  quick: [
    { label: 'Plate solving', enabled: false },
    { label: 'Gradient removal', enabled: false },
    { label: 'Color calibration', enabled: false },
    { label: 'Denoise (0.5)', enabled: true },
    { label: 'Sharpen', enabled: false },
    { label: 'Super-res', enabled: false },
    { label: 'Star separation', enabled: false },
  ],
  standard: [
    { label: 'Plate solving', enabled: true },
    { label: 'Gradient removal (AI)', enabled: true },
    { label: 'Color calibration', enabled: true },
    { label: 'Denoise (luminance, 0.55)', enabled: true },
    { label: 'Sharpen', enabled: true },
    { label: 'Super-res', enabled: false },
    { label: 'Star separation', enabled: false },
  ],
  quality: [
    { label: 'Drizzle ×2', enabled: true },
    { label: 'Plate solving', enabled: true },
    { label: 'Gradient removal (AI)', enabled: true },
    { label: 'Color calibration', enabled: true },
    { label: 'Denoise (luminance, 0.65)', enabled: true },
    { label: 'Sharpen', enabled: true },
    { label: 'Super-res ×2 (opt-in)', enabled: false },
    { label: 'Star separation (opt-in)', enabled: false },
  ],
};

export const DEFAULT_ADVANCED_CONFIG: ProcessingProfileConfig = { ...PRESET_DEFAULTS.standard };
