import { Link } from 'react-router-dom';
import {
  ArrowRight,
  BookOpen,
  Camera,
  Crosshair,
  Layers,
  LifeBuoy,
  Moon,
  MoonStar,
  RefreshCcw,
  Sparkles,
  Sun,
  Telescope,
  Wand2,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import { SectionHeading } from '../components/landing/SectionHeading';

interface FrameType {
  icon: LucideIcon;
  name: string;
  purpose: string;
  count: string;
  exposure: string;
  reusable: 'Single-use' | 'Reusable' | 'Long-term reusable';
  notes: string;
}

const FRAME_TYPES: FrameType[] = [
  {
    icon: Telescope,
    name: 'Light frames',
    purpose:
      'The actual photons from your target — every faint nebula tendril or galaxy arm comes from these subs.',
    count: '30 – 100+ subs',
    exposure: 'Longest exposure your mount can track without star trails (60 s – 5 min typical).',
    reusable: 'Single-use',
    notes:
      'Captured during the imaging session itself. More integration time = cleaner final image.',
  },
  {
    icon: Moon,
    name: 'Dark frames',
    purpose:
      'Map the thermal signal and hot pixels generated by the sensor when it heats up during long exposures.',
    count: '20 – 40 subs',
    exposure: 'Identical exposure, ISO/gain and sensor temperature as your lights, lens cap on.',
    reusable: 'Reusable',
    notes:
      'Build a dark library you can reuse across sessions, but only while temperature, exposure and gain stay matched.',
  },
  {
    icon: Sun,
    name: 'Flat frames',
    purpose:
      'Reveal vignetting, dust motes and uneven illumination across the optical train so they can be divided out.',
    count: '20 – 30 subs',
    exposure: 'Short exposure aimed at a uniform light source (sky panel, T-shirt method, dawn sky).',
    reusable: 'Single-use',
    notes:
      'Must be captured without disturbing focus, camera rotation or filter — recapture if anything in the imaging train moves.',
  },
  {
    icon: MoonStar,
    name: 'Dark-flat frames',
    purpose:
      'Calibrate the bias and read noise specifically present in your flat frames.',
    count: '20 – 30 subs',
    exposure: 'Same exposure as your flats, lens cap on. Often replaces bias frames for CMOS sensors.',
    reusable: 'Reusable',
    notes:
      'Only valid alongside the flat library they were taken with — store them together.',
  },
  {
    icon: Zap,
    name: 'Bias / Offset frames',
    purpose:
      'Capture the read-out noise floor of the sensor — the signal present even in a zero-second exposure.',
    count: '50 – 100 subs',
    exposure: 'The shortest exposure your camera supports, lens cap on.',
    reusable: 'Long-term reusable',
    notes:
      'Build once per camera/gain combination and reuse for months. Modern CMOS workflows often skip bias in favour of dark-flats.',
  },
];

interface ReuseRow {
  library: string;
  invalidatedBy: string;
  shelfLife: string;
}

const REUSE_MATRIX: ReuseRow[] = [
  {
    library: 'Lights',
    invalidatedBy: 'Always single-use — they are the data of one specific session.',
    shelfLife: 'One target, one session.',
  },
  {
    library: 'Darks',
    invalidatedBy: 'Sensor temperature drift, exposure change, ISO/gain change.',
    shelfLife: 'Months, if temperature is regulated (cooled cameras).',
  },
  {
    library: 'Flats',
    invalidatedBy: 'Focus shift, camera rotation, filter swap, dust motes moving.',
    shelfLife: 'Single imaging-train configuration, typically one night.',
  },
  {
    library: 'Dark-flats',
    invalidatedBy: 'Anything that invalidates the flats they belong to.',
    shelfLife: 'Tied to their flat library.',
  },
  {
    library: 'Bias / Offset',
    invalidatedBy: 'Camera or gain change.',
    shelfLife: 'Long-term — months to years per camera/gain pair.',
  },
];

interface PipelineStep {
  machine: string;
  title: string;
  engine: string;
  description: string;
}

const PIPELINE_STEPS: PipelineStep[] = [
  {
    machine: 'raw_conversion',
    title: 'RAW → FITS conversion',
    engine: 'AstroStack',
    description:
      'Decodes camera RAW files (CR2, NEF, ARW, DNG…) into the scientific FITS format expected by every downstream tool, preserving the full bit depth of the sensor.',
  },
  {
    machine: 'preprocessing',
    title: 'Calibration & stacking',
    engine: 'Siril (headless)',
    description:
      'Builds master darks, flats and bias from your calibration frames, applies them to every light, registers the subs on the same star pattern and stacks them to dramatically improve the signal-to-noise ratio.',
  },
  {
    machine: 'plate_solving',
    title: 'Plate solving',
    engine: 'ASTAP',
    description:
      'Identifies the exact patch of sky your image covers by matching star positions against an astrometric catalog. Coordinates and orientation are written into the FITS header and used by later steps.',
  },
  {
    machine: 'gradient_removal',
    title: 'Background gradient removal',
    engine: 'GraXpert',
    description:
      'Detects and subtracts the smooth light-pollution and Moon glow gradients that wash out faint structures, leaving a flat, neutral background to stretch from.',
  },
  {
    machine: 'stretch_color',
    title: 'Stretch & colour calibration',
    engine: 'Siril',
    description:
      'Re-maps the linear sensor data into a viewable image: faint nebulosity becomes visible, while photometric colour calibration uses catalog star colours to set a scientifically neutral white balance.',
  },
  {
    machine: 'denoise',
    title: 'AI noise reduction',
    engine: 'Cosmic Clarity',
    description:
      'A neural network trained on astrophotography data smooths out background grain without softening real stars or nebula details — far gentler than generic photo denoisers.',
  },
  {
    machine: 'sharpen',
    title: 'AI sharpening / deconvolution',
    engine: 'Cosmic Clarity',
    description:
      'Recovers detail lost to seeing, focus and tracking imperfections. Stars become tighter and structures crisper without amplifying noise.',
  },
  {
    machine: 'super_resolution',
    title: 'AI super-resolution (2×)',
    engine: 'Cosmic Clarity',
    description:
      'Doubles the linear resolution of the frame using a model trained to hallucinate plausible high-frequency detail — useful for small targets or short focal lengths.',
  },
  {
    machine: 'star_separation',
    title: 'Star separation',
    engine: 'Cosmic Clarity (Dark Star)',
    description:
      'Splits the image into a starless layer and a stars-only layer so each can be processed independently. This is the trick behind most modern nebula renderings where stars feel small but the gas glows.',
  },
  {
    machine: 'export',
    title: 'Export',
    engine: 'AstroStack',
    description:
      'Writes the final master to FITS (for re-processing), TIFF (for editing) and JPEG (for sharing), and renders a thumbnail for the gallery.',
  },
];

interface Tip {
  icon: LucideIcon;
  title: string;
  body: string;
}

const TIPS: Tip[] = [
  {
    icon: Crosshair,
    title: 'Nail focus first',
    body: 'A Bahtinov mask takes thirty seconds and is the single biggest jump in star quality you can get for free.',
  },
  {
    icon: RefreshCcw,
    title: 'Dither between subs',
    body: 'Small random offsets between exposures let stacking reject hot pixels and walking noise — your darks do less work and the result is cleaner.',
  },
  {
    icon: Layers,
    title: 'Capture order',
    body: 'Lights first, then flats before you tear down the rig (so the optical train is undisturbed). Darks and bias can be shot any time the sensor temperature matches.',
  },
  {
    icon: Camera,
    title: 'Match calibration to lights',
    body: 'Same exposure, same ISO/gain, same temperature for darks. Same focus and rotation for flats. Mismatches add noise instead of removing it.',
  },
  {
    icon: Sparkles,
    title: 'Start with bright targets',
    body: 'M42 (Orion), M31 (Andromeda), M45 (Pleiades) and the Veil Nebula forgive short integration times and tracking errors — perfect first projects.',
  },
  {
    icon: Wand2,
    title: 'Profiles over fiddling',
    body: 'Pick a Quality preset and let the pipeline run end-to-end before you start tuning. Compare runs, then adjust one parameter at a time.',
  },
];

const TOC = [
  { href: '#frames', label: 'Frame types' },
  { href: '#calibration-reuse', label: 'Reuse cheat sheet' },
  { href: '#pipeline', label: 'Pipeline' },
  { href: '#tips', label: 'Beginner tips' },
];

export function Learn() {
  return (
    <div className="bg-space-bg text-text-primary">
      <Hero />
      <Primer />
      <Frames />
      <ReuseCheatSheet />
      <Pipeline />
      <Tips />
      <FinalCta />
    </div>
  );
}

function Hero() {
  return (
    <section className="relative border-b border-space-border overflow-hidden">
      <div
        className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,rgba(99,102,241,0.10),transparent_70%)]"
        aria-hidden="true"
      />
      <div className="relative max-w-4xl mx-auto px-6 py-20 sm:py-24 text-center space-y-6">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-space-border bg-space-elevated/40 text-[11px] uppercase tracking-[0.18em] font-semibold text-accent">
          <BookOpen size={12} />
          Learn the basics
        </div>
        <h1 className="text-4xl sm:text-5xl font-semibold tracking-tight leading-[1.05]">
          Astrophotography,{' '}
          <span className="text-gradient-accent">decoded.</span>
        </h1>
        <p className="text-base sm:text-lg text-text-secondary max-w-2xl mx-auto leading-relaxed">
          A short guide to the frames you should be capturing and what
          AstroStack actually does to them — written for first-time
          astrophotographers.
        </p>
        <nav className="flex flex-wrap items-center justify-center gap-2 pt-2">
          {TOC.map((item) => (
            <a
              key={item.href}
              href={item.href}
              className="text-xs px-3 py-1.5 rounded-md border border-space-border bg-space-elevated/40 text-text-secondary hover:text-text-primary hover:border-white/15 transition-colors"
            >
              {item.label}
            </a>
          ))}
        </nav>
      </div>
    </section>
  );
}

function Primer() {
  return (
    <section className="border-b border-space-border bg-space-bg">
      <div className="max-w-4xl mx-auto px-6 py-14 sm:py-16">
        <SectionHeading
          kicker="Why calibration matters"
          title="A single frame is mostly noise."
          subtitle="Camera sensors generate thermal noise, vignette toward the edges and accumulate dust on every optical surface. Calibration frames measure those defects so the stacker can subtract them — and stacking many lights averages out the random noise the calibration can't remove."
        />
      </div>
    </section>
  );
}

function Frames() {
  return (
    <section id="frames" className="border-b border-space-border bg-space-bg scroll-mt-16">
      <div className="max-w-6xl mx-auto px-6 py-20 sm:py-24 space-y-12">
        <SectionHeading
          kicker="The five frame types"
          title="Every astrophoto is a stack of these."
          subtitle="Lights are your data. Darks, flats, dark-flats and bias are calibration frames that tell the stacker how to clean each light up."
        />
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {FRAME_TYPES.map((frame) => (
            <FrameCard key={frame.name} frame={frame} />
          ))}
        </div>
      </div>
    </section>
  );
}

function FrameCard({ frame }: { frame: FrameType }) {
  const Icon = frame.icon;
  const badgeStyle =
    frame.reusable === 'Single-use'
      ? 'bg-error/10 border-error/25 text-error'
      : frame.reusable === 'Long-term reusable'
        ? 'bg-success/10 border-success/25 text-success'
        : 'bg-accent/10 border-accent/25 text-accent';

  return (
    <article className="group rounded-xl border border-space-border bg-space-elevated/40 p-5 hover:border-white/15 hover:bg-space-elevated/70 transition-colors flex flex-col gap-4">
      <header className="flex items-start justify-between gap-3">
        <div className="w-9 h-9 rounded-lg bg-primary/10 border border-primary/20 flex items-center justify-center text-primary">
          <Icon size={17} />
        </div>
        <span
          className={`text-[10px] uppercase tracking-wider font-semibold px-2 py-1 rounded-md border ${badgeStyle}`}
        >
          {frame.reusable}
        </span>
      </header>
      <div className="space-y-1.5">
        <h3 className="text-base font-semibold text-text-primary">{frame.name}</h3>
        <p className="text-sm text-text-secondary leading-relaxed">{frame.purpose}</p>
      </div>
      <dl className="space-y-2 text-xs border-t border-space-border pt-3">
        <div className="flex items-baseline gap-2">
          <dt className="text-text-muted uppercase tracking-wider w-20 flex-shrink-0">Count</dt>
          <dd className="text-text-secondary">{frame.count}</dd>
        </div>
        <div className="flex items-baseline gap-2">
          <dt className="text-text-muted uppercase tracking-wider w-20 flex-shrink-0">Exposure</dt>
          <dd className="text-text-secondary">{frame.exposure}</dd>
        </div>
        <div className="flex items-baseline gap-2">
          <dt className="text-text-muted uppercase tracking-wider w-20 flex-shrink-0">Notes</dt>
          <dd className="text-text-secondary">{frame.notes}</dd>
        </div>
      </dl>
    </article>
  );
}

function ReuseCheatSheet() {
  return (
    <section
      id="calibration-reuse"
      className="border-b border-space-border bg-gradient-to-b from-space-bg to-space-elevated/20 scroll-mt-16"
    >
      <div className="max-w-5xl mx-auto px-6 py-20 sm:py-24 space-y-10">
        <SectionHeading
          kicker="Cheat sheet"
          title="What invalidates a calibration library?"
          subtitle="The good news: most calibration frames can be reused for weeks or months. The bad news: a handful of changes silently make them useless, so the rules below are worth memorising."
        />
        <div className="overflow-x-auto rounded-xl border border-space-border bg-space-elevated/40">
          <table className="w-full text-sm">
            <thead>
              <tr className="text-left text-text-muted text-xs uppercase tracking-wider border-b border-space-border">
                <th className="px-4 py-3 font-semibold">Library</th>
                <th className="px-4 py-3 font-semibold">Invalidated by</th>
                <th className="px-4 py-3 font-semibold">Typical shelf life</th>
              </tr>
            </thead>
            <tbody>
              {REUSE_MATRIX.map((row, idx) => (
                <tr
                  key={row.library}
                  className={
                    idx === REUSE_MATRIX.length - 1
                      ? ''
                      : 'border-b border-space-border/60'
                  }
                >
                  <td className="px-4 py-3 font-medium text-text-primary whitespace-nowrap">
                    {row.library}
                  </td>
                  <td className="px-4 py-3 text-text-secondary leading-relaxed">
                    {row.invalidatedBy}
                  </td>
                  <td className="px-4 py-3 text-text-secondary leading-relaxed">
                    {row.shelfLife}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </section>
  );
}

function Pipeline() {
  return (
    <section id="pipeline" className="border-b border-space-border bg-space-bg scroll-mt-16">
      <div className="max-w-5xl mx-auto px-6 py-20 sm:py-24 space-y-12">
        <SectionHeading
          kicker="Inside the pipeline"
          title="What AstroStack does to your stack."
          subtitle="Each session runs through these ten steps in order. You can resume from any failed step without re-running the ones that already succeeded."
        />
        <ol className="space-y-3">
          {PIPELINE_STEPS.map((step, idx) => (
            <li
              key={step.machine}
              className="rounded-xl border border-space-border bg-space-elevated/40 hover:bg-space-elevated/60 transition-colors p-5 flex gap-4"
            >
              <span className="flex-shrink-0 w-9 h-9 rounded-lg bg-primary/10 border border-primary/20 text-primary text-sm font-semibold flex items-center justify-center">
                {idx + 1}
              </span>
              <div className="space-y-1.5 min-w-0">
                <div className="flex items-baseline flex-wrap gap-x-3 gap-y-1">
                  <h3 className="text-base font-semibold text-text-primary">
                    {step.title}
                  </h3>
                  <span className="text-[10px] uppercase tracking-wider font-semibold text-accent">
                    {step.engine}
                  </span>
                  <code className="text-[11px] text-text-muted font-mono">
                    {step.machine}
                  </code>
                </div>
                <p className="text-sm text-text-secondary leading-relaxed">
                  {step.description}
                </p>
              </div>
            </li>
          ))}
        </ol>
      </div>
    </section>
  );
}

function Tips() {
  return (
    <section id="tips" className="border-b border-space-border bg-space-bg scroll-mt-16">
      <div className="max-w-6xl mx-auto px-6 py-20 sm:py-24 space-y-12">
        <SectionHeading
          kicker="Field notes"
          title="Six habits that will save you a night."
          subtitle="The advice astrophotographers wish someone had handed them on day one."
        />
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {TIPS.map((tip) => {
            const Icon = tip.icon;
            return (
              <article
                key={tip.title}
                className="rounded-xl border border-space-border bg-space-elevated/40 p-5 hover:border-white/15 transition-colors"
              >
                <div className="w-9 h-9 rounded-lg bg-primary/10 border border-primary/20 flex items-center justify-center text-primary mb-4">
                  <Icon size={17} />
                </div>
                <h3 className="text-base font-semibold text-text-primary mb-1.5">
                  {tip.title}
                </h3>
                <p className="text-sm text-text-secondary leading-relaxed">
                  {tip.body}
                </p>
              </article>
            );
          })}
        </div>
      </div>
    </section>
  );
}

function FinalCta() {
  return (
    <section className="bg-space-bg">
      <div className="max-w-3xl mx-auto px-6 py-20 sm:py-24 text-center space-y-6">
        <h2 className="text-3xl sm:text-4xl font-semibold tracking-tight">
          Ready for your first stack?
        </h2>
        <p className="text-text-secondary">
          Browse what other astronomers have published, or sign in and run your
          own subs through the pipeline.
        </p>
        <div className="flex flex-wrap items-center justify-center gap-3">
          <Link
            to="/login"
            className="group inline-flex items-center gap-2 rounded-md bg-primary px-5 py-2.5 text-sm font-medium text-white hover:bg-primary-hover transition-colors"
          >
            Get started
            <ArrowRight
              size={15}
              className="transition-transform group-hover:translate-x-0.5"
            />
          </Link>
          <Link
            to="/gallery"
            className="inline-flex items-center gap-2 rounded-md border border-white/15 bg-white/[0.04] px-5 py-2.5 text-sm font-medium text-white hover:bg-white/[0.08] hover:border-white/25 transition-colors"
          >
            Browse the gallery
          </Link>
        </div>
        <p className="text-xs text-text-muted pt-4 inline-flex items-center gap-1.5 justify-center">
          <LifeBuoy size={12} />
          Stuck? Open an issue on GitHub and we'll help.
        </p>
      </div>
    </section>
  );
}
